quarkus:
  banner:
    enabled: false
  native:
    resources:
      includes: META-INF/resources/redlab-logo.png
  log:
    level: WARN
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"